### ISSUE TITLE
ansible failed to complete successfully. any error output should be visible above. Please fix these errors and try again

### ISSUE THREAD

**Issue by sepehrafla** [splunk/attack_range_local#35]
I am getting this error would appreciate a guide 
"ansible failed to complete successfully. any error output should be visible above. Please fix these errors and try again"
for phantom and windows domain controller machines. 
my ansible version is 2.9.2
vagrant 2.2.14
virtualbox = 5.2.42

The complete error is :
```
==> attack-range-windows-domain-controller: Checking if box 'd1vious/windows2016' version '1.0' is up to date...
==> attack-range-windows-domain-controller: Running provisioner: ansible...
  attack-range-windows-domain-controller: Running ansible-playbook...
PLAY [all] *********************************************************************
TASK [Gathering Facts] *********************************************************
fatal: [attack-range-windows-domain-controller]: UNREACHABLE! => {"changed": false, "msg": "plaintext: the specified credentials were rejected by the server", "unreachable": true}
PLAY RECAP *********************************************************************
attack-range-windows-domain-controller : ok=0  changed=0  unreachable=1  failed=0  skipped=0  rescued=0  ignored=0  
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
2021-02-03 15:37:01,191 - ERROR - attack_range - vagrant failed to build
```

**Comment by kseidenschnur** [comment]
@sepehrafla Hi, have you been able to sucessfully build attack range before? I have seen cases where whenever I rebuild an environtment (images don't need to be downloaded) causing the error right after the splunk machine was build. I had the feeling that my machine was so busy with the splunk machine that the windows machine became unresponive. I was not able to reproduce 100%. But was able to avoid that problem by deleting my vagrant images. So that they need to be downloaded during build process. Simply to give the machines a little bit more time before the next machine is build.
If that helps, we might be able to ingerate som sort of timer to avoid that problem in the future.

**Comment by youda313** [comment]
I have the same issue, I was able to build the range in a close past, but now I can't build the DC
